apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nucleus-dev
  name: nucleus-nodeport
  namespace: nucleus-dev
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    nodePort: 31759
    port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: nucleus-dev
    type: web
  sessionAffinity: None
  type: NodePort
status:
  # existing ELB managed by tf not k8s
  loadBalancer: {}
