apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
  namespace: nucleus-prod
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: it-se@mozilla.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nucleus-prod-ingress
  namespace: nucleus-prod
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: nucleus-prod
    type: web
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt
  name: nucleus-prod
  namespace: nucleus-prod
spec:
  rules:
    - host: "nucleus.prod.fr.moz.works"
      http:
        paths:
          - backend:
              serviceName: nucleus-prod-ingress
              servicePort: 8000
            path: /
    - host: "nucleus.moz.works"
      http:
        paths:
          - backend:
              serviceName: nucleus-prod-ingress
              servicePort: 8000
            path: /
    - host: "nucleus.mozilla.org"
      http:
        paths:
          - backend:
              serviceName: nucleus-prod-ingress
              servicePort: 8000
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
      - hosts:
          - "nucleus.prod.fr.moz.works"
          - "nucleus.moz.works"
          - "nucleus.mozilla.org"
        secretName: nucleus-tls
